const axios = require('axios');

/**
 * Resource Search Service
 *
 * Finds real, high-quality YouTube videos and authoritative documentation
 * based on precise search queries generated by the AI evaluation.
 *
 * Never fabricates YouTube URLs or thumbnails.
 */

/**
 * Search YouTube for a specific query and return ranked real video metadata.
 */
async function searchYouTubeVideo(searchQuery, gapTitle = '') {
  if (!searchQuery) return null;

  const cleanQuery = searchQuery.trim();

  // 1. Try YouTube Data API v3 if API key is provided
  if (process.env.YOUTUBE_API_KEY) {
    try {
      const ytRes = await axios.get('https://www.googleapis.com/youtube/v3/search', {
        params: {
          key: process.env.YOUTUBE_API_KEY,
          q: cleanQuery,
          part: 'snippet',
          type: 'video',
          videoEmbeddable: 'true',
          maxResults: 5,
          order: 'relevance',
          safeSearch: 'moderate'
        },
        timeout: 10000
      });

      const items = ytRes.data?.items || [];
      if (items.length > 0) {
        const best = rankYouTubeItems(items, cleanQuery);
        if (best) {
          const videoId = best.id?.videoId || best.id;
          const snippet = best.snippet || {};
          return {
            title: snippet.title || cleanQuery,
            video_id: videoId,
            youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
            thumbnail_url: snippet.thumbnails?.high?.url || snippet.thumbnails?.medium?.url || `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
            channel_name: snippet.channelTitle || 'YouTube Educator',
            description: snippet.description || '',
            published_at: snippet.publishedAt ? new Date(snippet.publishedAt).toLocaleDateString() : '',
            duration: '~1-2 hours',
            resource_type: 'youtube_video',
            matched_gap: gapTitle || cleanQuery
          };
        }
      }
    } catch (err) {
      console.warn('[ResourceSearch] YouTube Data API error:', err.message);
    }
  }

  // 2. Direct Scraper / Search Endpoint fallback (extracts real video IDs from YouTube search results)
  try {
    const searchUrl = `https://www.youtube.com/results?search_query=${encodeURIComponent(cleanQuery)}`;
    const scrapeRes = await axios.get(searchUrl, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept-Language': 'en-US,en;q=0.9'
      },
      timeout: 10000
    });

    if (scrapeRes.data && typeof scrapeRes.data === 'string') {
      const match = scrapeRes.data.match(/ytInitialData\s*=\s*({.+?});<\/script>/);
      if (match && match[1]) {
        try {
          const ytData = JSON.parse(match[1]);
          const contents = ytData?.contents?.twoColumnSearchResultsRenderer?.primaryContents?.sectionListRenderer?.contents;
          const videoItems = [];

          if (Array.isArray(contents)) {
            for (const section of contents) {
              const itemSection = section?.itemSectionRenderer?.contents || [];
              for (const it of itemSection) {
                if (it.videoRenderer) {
                  const vr = it.videoRenderer;
                  const vidId = vr.videoId;
                  const title = vr.title?.runs?.map(r => r.text).join('') || vr.title?.simpleText;
                  const channel = vr.ownerText?.runs?.map(r => r.text).join('') || vr.shortBylineText?.runs?.map(r => r.text).join('');
                  const duration = vr.lengthText?.simpleText || '';
                  const published = vr.publishedTimeText?.simpleText || '';
                  const description = vr.detailedMetadataSnippets?.[0]?.snippetText?.runs?.map(r => r.text).join('') || '';

                  if (vidId && title) {
                    videoItems.push({
                      videoId: vidId,
                      title,
                      channel,
                      duration,
                      published,
                      description,
                      thumbnail: `https://i.ytimg.com/vi/${vidId}/hqdefault.jpg`
                    });
                  }
                }
              }
            }
          }

          if (videoItems.length > 0) {
            const best = videoItems[0];
            return {
              title: best.title,
              video_id: best.videoId,
              youtube_url: `https://www.youtube.com/watch?v=${best.videoId}`,
              thumbnail_url: best.thumbnail,
              channel_name: best.channel || 'YouTube Educator',
              description: best.description || '',
              published_at: best.published || '',
              duration: best.duration || '~1 hour',
              resource_type: 'youtube_video',
              matched_gap: gapTitle || cleanQuery
            };
          }
        } catch (parseErr) {
          // JSON parse fallback
        }
      }
    }
  } catch (err) {
    console.warn('[ResourceSearch] Direct YouTube search warning:', err.message);
  }

  // 3. Fallback to Tavily search for YouTube videos if available
  if (process.env.TAVILY_API_KEY) {
    try {
      const tavilyRes = await axios.post('https://api.tavily.com/search', {
        api_key: process.env.TAVILY_API_KEY,
        query: `site:youtube.com/watch ${cleanQuery}`,
        search_depth: 'basic',
        max_results: 3
      }, { timeout: 8000 });

      const results = tavilyRes.data?.results || [];
      for (const res of results) {
        const vidMatch = res.url?.match(/(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/);
        if (vidMatch && vidMatch[1]) {
          const videoId = vidMatch[1];
          return {
            title: res.title || cleanQuery,
            video_id: videoId,
            youtube_url: `https://www.youtube.com/watch?v=${videoId}`,
            thumbnail_url: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
            channel_name: 'YouTube Educator',
            description: res.content || '',
            published_at: '',
            duration: '~1 hour',
            resource_type: 'youtube_video',
            matched_gap: gapTitle || cleanQuery
          };
        }
      }
    } catch (tavErr) {
      console.warn('[ResourceSearch] Tavily YouTube search warning:', tavErr.message);
    }
  }

  // 4. If all live video searches fail, return clean search URL without inventing fake video IDs
  return {
    title: `${cleanQuery} - Recommended Learning Search`,
    video_id: null,
    youtube_url: `https://www.youtube.com/results?search_query=${encodeURIComponent(cleanQuery)}`,
    thumbnail_url: null,
    channel_name: 'YouTube Search',
    description: `Search results for ${cleanQuery}`,
    published_at: '',
    duration: '',
    resource_type: 'youtube_search',
    matched_gap: gapTitle || cleanQuery
  };
}

/**
 * Rank YouTube items to select the best tutorial/educational match.
 */
function rankYouTubeItems(items, query) {
  if (!items.length) return null;
  const qLower = query.toLowerCase();

  return items.slice().sort((a, b) => {
    const titleA = (a.snippet?.title || '').toLowerCase();
    const titleB = (b.snippet?.title || '').toLowerCase();

    // Prefer titles containing full tutorial / crash course / guide keywords
    const scoreA = (titleA.includes('tutorial') ? 3 : 0) +
                   (titleA.includes('course') ? 2 : 0) +
                   (titleA.includes('guide') ? 2 : 0) +
                   (qLower.split(' ').filter(w => titleA.includes(w)).length);

    const scoreB = (titleB.includes('tutorial') ? 3 : 0) +
                   (titleB.includes('course') ? 2 : 0) +
                   (titleB.includes('guide') ? 2 : 0) +
                   (qLower.split(' ').filter(w => titleB.includes(w)).length);

    return scoreB - scoreA;
  })[0];
}

/**
 * Curated authoritative documentation mapper.
 * Returns genuine, high-quality documentation links for common technologies.
 */
function getAuthoritativeDoc(technologyOrGap) {
  if (!technologyOrGap) return null;
  const t = technologyOrGap.toLowerCase();

  const DOCS_MAP = [
    { match: 'react', title: 'React Official Documentation', url: 'https://react.dev/learn', type: 'official_docs', why_useful: 'Official interactive React tutorial and component patterns', estimated_time: '2-4 hours' },
    { match: 'node', title: 'Node.js Official Guides', url: 'https://nodejs.org/en/learn', type: 'official_docs', why_useful: 'Official Node.js architecture and async programming guides', estimated_time: '2 hours' },
    { match: 'express', title: 'Express.js Routing & Middleware Guide', url: 'https://expressjs.com/en/guide/routing.html', type: 'official_docs', why_useful: 'REST API design and middleware best practices', estimated_time: '1 hour' },
    { match: 'typescript', title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs/handbook/intro.html', type: 'official_docs', why_useful: 'Type definitions, interfaces, and generic types in practice', estimated_time: '3 hours' },
    { match: 'mongodb', title: 'MongoDB University / Developer Docs', url: 'https://www.mongodb.com/docs/manual/tutorial/getting-started/', type: 'official_docs', why_useful: 'Schema design, indexes, and aggregation framework', estimated_time: '2 hours' },
    { match: 'sql', title: 'PostgreSQL Tutorial / SQL Practice', url: 'https://www.postgresqltutorial.com/', type: 'tutorial', why_useful: 'Relational data modeling, joins, and indexing', estimated_time: '3 hours' },
    { match: 'docker', title: 'Docker Get Started Guide', url: 'https://docs.docker.com/get-started/', type: 'official_docs', why_useful: 'Containerizing full-stack apps and Docker Compose setups', estimated_time: '2 hours' },
    { match: 'next', title: 'Next.js App Router Documentation', url: 'https://nextjs.org/docs', type: 'official_docs', why_useful: 'Server components, data fetching, and deployment', estimated_time: '3 hours' },
    { match: 'api', title: 'MDN Web APIs & Fetch Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch', type: 'official_docs', why_useful: 'HTTP requests, headers, and async handling in JavaScript', estimated_time: '1 hour' },
    { match: 'dsa', title: 'NeetCode Roadmap & Practice', url: 'https://neetcode.io/roadmap', type: 'practice', why_useful: 'Curated blind 75 problem sets by topic', estimated_time: '10-20 hours' }
  ];

  for (const doc of DOCS_MAP) {
    if (t.includes(doc.match)) {
      return doc;
    }
  }

  return {
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org',
    type: 'official_docs',
    why_useful: 'Standard web development and JavaScript reference',
    estimated_time: '1-2 hours'
  };
}

/**
 * Enriches learning recommendations with real YouTube videos and docs.
 */
async function enrichLearningRecommendations(recommendations = []) {
  if (!Array.isArray(recommendations) || recommendations.length === 0) {
    return [];
  }

  const enriched = [];
  for (const rec of recommendations) {
    const searchQuery = rec.search_query || `${rec.skill_gap || ''} project tutorial`;
    const ytResource = await searchYouTubeVideo(searchQuery, rec.skill_gap || rec.title);
    const authDoc = getAuthoritativeDoc(rec.skill_gap || rec.title || searchQuery);

    enriched.push({
      ...rec,
      youtube_resource: ytResource,
      authoritative_doc: authDoc
    });
  }

  return enriched;
}

module.exports = {
  searchYouTubeVideo,
  getAuthoritativeDoc,
  enrichLearningRecommendations
};
